### ISSUE TITLE
Looking to understand the current status, support, roadmap etc?

### ISSUE THREAD

**Issue by nodecentral** [andersardo/gedMerge#17]
Hi

Please could you let me know if this repo/code base is still actively being used and supported, it looks like a useful facility to have, just wanted to find out what the situation is with it.

Many thanks

**Comment by andersardo** [comment]
Hi,
   No I haven't been updating the repo since 2018.
However the have been updated and is in the process of being migrated to run on Ubuntu 22.04 (Python3, PHP 8, Mysql8, Lucene 9.7, MongoDB 7, ...). I'm going make a branch with the new code, but it's not ready or tested yet.
The code is in need of restructuring (and maybe re-writting) but there are no plans for that yet.

**Comment by andersardo** [comment]
Created branch 'migration' for the new code.
